eureka:
  image: springcloud/eureka
  container_name: eureka
  ports:
   - "8761:8761"
  net: "microservicesnet"
customer1:
  image: vprates/microservice
  container_name: customer1
  hostname: customer1
  net: "microservicesnet"
  ports:
   - "8080:8080"
  volumes:
   - D:/BSI/Corporativos/3bim/docker-handson-master:/data
  command: -jar /data/Customer-backend/target/Customer-backend-1.0.jar
product1:
  image: vprates/microservice
  container_name: product1
  hostname: product1
  net: "microservicesnet"
  ports:
   - "8081:8080"
  volumes:
   - D:/BSI/Corporativos/3bim/docker-handson-master:/data
  command: -jar /data/Product-backend/target/Product-backend-1.0.jar
order1:
  image: vprates/microservice
  container_name: order1
  hostname: order1
  net: "microservicesnet"
  ports:
   - "8082:8080"
  volumes:
   - D:/BSI/Corporativos/3bim/docker-handson-master:/data
  command: -jar /data/Order-backend/target/Order-backend-1.0.jar
